// vue/src/components/FeedbackRatings.vue
<template>
  <div :class="container">
    <div>
      <h2>{{title}}</h2>
    </div>
    <div :class="starList" data-rating="3">
      <span :class="star">&nbsp;</span>
      <span :class="star">&nbsp;</span>
      <span :class="star">&nbsp;</span>
      <span :class="star">&nbsp;</span>
      <span :class="star">&nbsp;</span>
    </div>
  </div>
</template>

<script>
export default {
  props: ["title", "starList", "star", "container"]
};
</script>

<style lang="scss" scoped>
</style>

// react/src/components/FeedbackRatings.js
import React, { Component } from 'react';

class FeedbackRatings extends Component {
	render() {
		return (
			<React.Fragment>
				<div className={this.props.class}>
					<div>
						<h2>{this.props.title}</h2>
					</div>
					<div className={this.props.starList} data-rating="3">
						<span className={this.props.star}>&nbsp;</span> <span className={this.props.star}>&nbsp;</span>
						<span className={this.props.star}>&nbsp;</span>
						<span className={this.props.star}>&nbsp;</span> <span className={this.props.star}>&nbsp;</span>
					</div>
				</div>
			</React.Fragment>
		);
	}
}

export default FeedbackRatings;
